apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-handler
  namespace: flask-project
  labels:
    app.kubernetes.io/component: event-handler
    app.kubernetes.io/name: event-handler
    app.kubernetes.io/part-of: flask-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: event-handler
  template:
    metadata:
      labels:
        application: event-handler
    spec:
      initContainers:
      containers:
        - name: event-handler
          env:
          image: docker.io/neerajtiwari/event-handler:5b4df3b10e9cadb6d5cbc3d145f0437495e7e9e1
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: 20m
              memory: 256Mi
            limits:
              cpu: 20m
              memory: 256Mi
