apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-handler
  namespace: event-handler
  labels:
    application: event-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      application: event-handler
  template:
    metadata:
      labels:
        application: event-handler
    spec:
      initContainers:
      containers:
        - name: event-handler
          env:
          image: docker.io/neerajtiwari/event-handler:97176696b90ece9100cf11b2cb4fba2dada48f93
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              cpu: 20m
              memory: 128Mi
