apiVersion: v1
kind: Service
metadata:
  name: event-handler
  namespace: event-handler
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: event-handler